name: Build Jappi88 Editor
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest  # Vamos rodar em Windows para gerar o .exe perfeito
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Solution
        run: msbuild "Dragon Age Inquisition Save Editor.sln" /p:Configuration=Release

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: DragonAgeEditor
          path: "Dragon Age Inquisition Save Editor/bin/Release/"
