name: Build Jappi88 Editor
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet Packages
        run: nuget restore "Dragon Age Inquisition Save Editor.sln"

      - name: Build Solution (Force Retarget)
        run: |
          msbuild "Dragon Age Inquisition Save Editor.sln" `
          /p:Configuration=Release `
          /p:Platform="Any CPU" `
          /p:TargetFrameworkVersion=v4.8 `
          /p:OutDir=BuildOutput/

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: DragonAgeEditor_Henrique
          path: "Dragon Age Inquisition Save Editor/BuildOutput/"
